<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.4</version>
  </parent>
  <groupId>com.pia.commons</groupId>
  <artifactId>pia-camunda-7</artifactId>
  <version>22.0.1-SNAPSHOT</version>
  <properties>
    <java.version>17</java.version>

    <!-- Application dependencies -->
    <camunda.version>7.22.0</camunda.version>
    <camunda-platform-7-keycloak.version>7.21.6</camunda-platform-7-keycloak.version>
    <camunda-spin.version>7.22.0</camunda-spin.version>
    <pia-security.version>1.0.2</pia-security.version>
    <camunda-incident-logger.version>1.0.1</camunda-incident-logger.version>
    <graalvm.version>23.0.5</graalvm.version>
    <logstash-logback-encoder.version>8.0</logstash-logback-encoder.version>

    <archunit.version>1.3.0</archunit.version>
    <testcontainers.version>1.19.8</testcontainers.version>

    <!-- Maven plugins -->
    <jacoco-maven-plugin.version>0.8.12</jacoco-maven-plugin.version>
    <maven-compiler-plugin-version>3.13.0</maven-compiler-plugin-version>
    <maven-failsafe-plugin-version>3.5.1</maven-failsafe-plugin-version>
    <maven-jar-plugin-version>3.4.2</maven-jar-plugin-version>
    <maven-resources-plugin-version>3.3.1</maven-resources-plugin-version>
    <maven-surefire-plugin-version>3.5.1</maven-surefire-plugin-version>
    <exec-maven-plugin.version>3.4.1</exec-maven-plugin.version>
    <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>

    <!-- Sonar properties -->
    <sonar.coverage.exclusions>**/PiaCamunda7Application.java</sonar.coverage.exclusions>
  </properties>

  <dependencies>

    <!-- Camunda Dependencies -->
    <dependency>
      <groupId>org.camunda.bpm.springboot</groupId>
      <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
      <version>${camunda.version}</version>
    </dependency>
    <dependency>
      <groupId>org.camunda.bpm.springboot</groupId>
      <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
      <version>${camunda.version}</version>
    </dependency>
    <dependency>
      <groupId>org.camunda.spin</groupId>
      <artifactId>camunda-spin-dataformat-json-jackson</artifactId>
      <version>${camunda-spin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.camunda.bpm</groupId>
      <artifactId>camunda-engine-plugin-spin</artifactId>
      <version>${camunda.version}</version>
    </dependency>
    <dependency>
      <groupId>org.camunda.bpm.extension</groupId>
      <artifactId>camunda-platform-7-keycloak</artifactId>
      <version>${camunda-platform-7-keycloak.version}</version>
    </dependency>
    <dependency>
      <groupId>com.pia.commons</groupId>
      <artifactId>camunda-incident-logger</artifactId>
      <version>${camunda-incident-logger.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js-scriptengine</artifactId>
      <version>${graalvm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js</artifactId>
      <version>${graalvm.version}</version>
      <scope>runtime</scope>
    </dependency>

    <!-- Pia OpenID Security -->
    <dependency>
      <groupId>com.pia.commons</groupId>
      <artifactId>pia-security</artifactId>
      <version>${pia-security.version}</version>
    </dependency>

    <!-- Database dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Monitoring dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

    <!-- Logging dependencies -->
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
      <version>${logstash-logback-encoder.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.janino</groupId>
      <artifactId>janino</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Test dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit-junit5</artifactId>
      <version>${archunit.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- Optional dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${maven-enforcer-plugin.version}</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.6.3</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <layers>
            <enabled>true</enabled>
            <includeLayerTools>true</includeLayerTools>
          </layers>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin-version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${maven-failsafe-plugin-version}</version>
        <configuration>
          <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${maven-jar-plugin-version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>${maven-resources-plugin-version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin-version}</version>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
          <execution>
            <id>coverage-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <haltOnFailure>false</haltOnFailure>
              <rules>
                <rule>
                  <element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <minimum>50%</minimum>
                      <value>COVEREDRATIO</value>
                    </limit>
                    <limit>
                      <counter>INSTRUCTION</counter>
                      <minimum>50%</minimum>
                      <value>COVEREDRATIO</value>
                    </limit>
                    <limit>
                      <counter>BRANCH</counter>
                      <minimum>50%</minimum>
                      <value>COVEREDRATIO</value>
                    </limit>
                    <limit>
                      <counter>CLASS</counter>
                      <maximum>0</maximum>
                      <value>MISSEDCOUNT</value>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>pia-commons-release</id>
      <layout>default</layout>
      <name>Maven RELEASE Repository for pia-commons</name>
      <releases>
        <checksumPolicy>warn</checksumPolicy>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-release/</url>
    </repository>
    <repository>
      <id>pia-commons-snapshot</id>
      <name>Maven SNAPSHOT Repository for pia-commons</name>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <checksumPolicy>warn</checksumPolicy>
        <enabled>true</enabled>
        <updatePolicy>interval:5</updatePolicy>
      </snapshots>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-snapshot/</url>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <id>pia-commons-release</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-release/</url>
    </repository>
    <snapshotRepository>
      <id>pia-commons-snapshot</id>
      <url>https://nexus.dnext-pia.com/repository/pia-commons-snapshot/</url>
    </snapshotRepository>
  </distributionManagement>

  <scm>
    <connection>scm:git:git@github.com:pia-commons/pia-camunda-7.git</connection>
    <developerConnection>scm:git:git@github.com:pia-commons/pia-camunda-7.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <profiles>
    <profile>
      <id>docker</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>${exec-maven-plugin.version}</version>
            <executions>
              <!-- Remove existing docker image from local repo -->
              <execution>
                <id>docker-clean</id>
                <phase>clean</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
                <configuration>
                  <executable>docker</executable>
                  <workingDirectory>${project.basedir}</workingDirectory>
                  <arguments>
                    <argument>image</argument>
                    <argument>rm</argument>
                    <argument>--force</argument>
                    <argument>local/${project.artifactId}:${project.version}</argument>
                  </arguments>
                </configuration>
              </execution>

              <!-- Create new docker image -->
              <execution>
                <id>docker-build</id>
                <phase>package</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
                <configuration>
                  <executable>docker</executable>
                  <workingDirectory>${project.basedir}</workingDirectory>
                  <arguments>
                    <argument>build</argument>
                    <argument>-t</argument>
                    <argument>local/${project.artifactId}:${project.version}</argument>
                    <argument>.</argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
