---
pia:
  security:
    jwk-set-uri: http://localhost:8000/realms/rehearsal-realm/protocol/openid-connect/certs
    user-claim: sub
    authorities-claim: groups
    secure-endpoints:
      - method: GET
        path: /engine-rest/**
        roles:
          - read
          - write
          - ENTERPRISE-GUI/ADMIN_ALL
          - ENTERPRISE-API/ADMIN_ALL
      - method: POST
        path: /engine-rest/**
        roles:
          - write
          - ENTERPRISE-GUI/ADMIN_ALL
          - ENTERPRISE-API/ADMIN_ALL
      - method: PUT
        path: /engine-rest/**
        roles:
          - write
          - ENTERPRISE-GUI/ADMIN_ALL
          - ENTERPRISE-API/ADMIN_ALL
      - method: DELETE
        path: /engine-rest/**
        roles:
          - write
          - ENTERPRISE-GUI/ADMIN_ALL
          - ENTERPRISE-API/ADMIN_ALL

    whitelist:
      - /error
      - /camunda/**
      - /engine-rest/external-task/**
      - /actuator
      - /actuator/**
