---
opentmf:
  security:
    jwk-set-uri: ${plugin.identity.keycloak.keycloak-issuer-url}/protocol/openid-connect/certs
    user-claim: email
    authorities-claim: groups
    secure-endpoints:
      - method: GET
        path: /engine-rest/**
        roles:
          - read
          - write
          - admin
      - method: POST
        path: /engine-rest/**
        roles:
          - write
          - admin
      - method: PUT
        path: /engine-rest/**
        roles:
          - write
          - admin
      - method: DELETE
        path: /engine-rest/**
        roles:
          - write
          - admin

      # Actuator Endpoints That Require Authorization
      - method: GET
        path: /actuator/env
        roles:
          - admin
      - method: GET
        path: /actuator/env/**
        roles:
          - admin

    whitelist:
      - /error
      - /camunda/**
      - /engine-rest/external-task/**
      - /actuator
      - /actuator/health/**
      - /actuator/loggers/**
      - /actuator/metrics/**
